= SIGMOD Programming Contest Archive
:revdate: 2024-04-27
:page-layout: index
:page-aggregate: true

SIGMOD hosts a yearly competition to design a system which performs a set of queries as quickly as possible.  Each contest provides a starting framework and test harness.  They also make great intermediate database projects for learning.

== Recent Contests

=== http://sigmodcontest2024.eastus.cloudapp.azure.com/index.shtml[Hybrid Vector Search (2024)]

=== https://people.cs.rutgers.edu/~dd903/sigmodpc2023/[Approximate K-nearest-neighbor Graph Construction (2023)]

=== https://dbgroup.ing.unimore.it/sigmod22contest/[Blocking System for Entity Resolution (2022)]

=== https://dbgroup.ing.unimo.it/sigmod21contest/[Entity Resolution (2021)]

=== https://www.inf.uniroma3.it/db/sigmod2020contest/index.html[Entity Resolution (2020)]

== Archived Contests

Unfortunately, the programming contest sites have been dropping off the internet as old year-specific SIGMOD domains are released or universities revamp their sites and drop old pages.  The challenges have generally been quite interesting projects, and every year someone puts good effort into providing a starting framework and testing harness for each challenge.  So to ensure these challenges remain easily accessible and available, I've located the original task description and source for each year, and copied them into the pages below to preserve the content.

++++
<%= partial("partials/index_section", :locals => {}) %>
++++

The code challenges are all issued with an MIT (or equivalently permissive) license.  The task description is... probably copyrighted?  (I don't make any money off this site. ACM, please don't sue me?)  Reach out to <domain of this site @ google mail provider> if you'd like to request a challenge be taken down.
