= SIGMOD Programming Contest Archive
:revdate: 2024-04-27
:page-layout: index
:page-aggregate: true

SIGMOD hosts a yearly competition to design a system which performs a set of queries as quickly as possible.  The contests provide a starting framework and test harness.  They make great intermediate database projects for learning.

== Recent Contests

=== http://sigmodcontest2024.eastus.cloudapp.azure.com/index.shtml[Hybrid Vector Search (2024)]

=== https://people.cs.rutgers.edu/~dd903/sigmodpc2023/[Approximate K-nearest-neighbor Graph Construction (2023)]

== Archived Contests

Unfortunately, the programming contest sites have been dropping off the internet as old year-specific SIGMOD domains are released or universities revamp their sites and drop old pages.  The challenges have generally been quite interesting projects, and every year someone puts good effort into providing a starting framework and testing harness for each challenge.  So to ensure these challenges remain easily accessible and available, I've located the original task description and source for each year, and copied them into the pages below to preserve the content.

++++
<%= partial("partials/index_section", :locals => {}) %>
++++

If you're reading this and are a former contestant, and you happen to have starting or test harness code which is missing in the linked GitHub repos, please reach out or send a PR.  If you attempt a challenge and have some improvements to the starting framework, test harness, or test data to provide, feel free to send a PR as well.

The code challenges are all issued with an MIT (or equivalently permissive) license.  (I don't make any money off this site. ACM, please don't sue me?)  Reach out to <domain of this site @ google mail provider> if you'd like to request a challenge be taken down.
