= Concurrent Operation Diagram Generator
:revdate: 16-12-2022
:page-features: python_wasm, alpine
:page-hook-preamble: false

The diagrams in https://cs.brown.edu/~mph/HerlihyW90/p463-herlihy.pdf[Linearizability: A Correctness Condition for Concurrent Objects] are a nice example of how to show how multiple concurrent operations overlap, and the possibilities for orderings that arise.  If you'd like to be able to make similar diagrams, there's a script that can generate them from a simple text-based description of the operations. 

== Demo

++++
<script>
var getPyodide = (function PyodideFetcher() {
    var result;
    return async function() {
      if (result) {
        return result;
      }
      let pyodide = await loadPyodide();
      await pyodide.loadPackage('/static/dbdiag.whl');
      result = pyodide;
      return pyodide;
    };
})();

async function ops_to_svg(ops, embed) {
  try {
    let dbdiag = (await getPyodide()).pyimport("dbdiag");
    let ret = dbdiag.to_span_svg.callKwargs(ops, {'embed': embed});
    dbdiag.destroy();
  return ret;
  } catch (e) {
    return "<p>" + e.toString() + "</p>";
  }
};
</script>

<div x-data="{ ops: 'Actor: Start A\nActor: End A', embed: false }">
<table>
  <colgroup>
    <col style="width: 40%">
    <col style="width: 60%">
  </colgroup>
  <tr>
    <td>
      <textarea x-model.debounce="ops" rows=10 cols=20 x-bind:placeholder="ops">
      </textarea>
      <span style="display: block">
        <input x-model="embed" type="checkbox" id="embed" />
        <label style="display: inline" for="embed">Force px for older browsers</label>
      </span>
    </td>
    <td>
      <span x-html="await ops_to_svg(ops, embed)">
      Loading...
      </span>
    </td>
  </tr>
</table>
</div>
++++

== Examples

`dbdiag-spans` visualizes operations performed by actors, with the x-axis implicitly being time moving forwards.

[cols="1,3"]
|===
a|----
Actor: Start A
Actor: End A
----
a|[dbdiag-spans]
----
Actor: Start A
Actor: End A
----
|===

You may label either the start and end, or the overall operation:

[cols="1,3"]
|===
a|----
Actor: Operation A
Actor: END A
----
.^a|[dbdiag-spans]
----
Actor: Operation A
Actor: END A
----
|===

Operations can be performed by multiple actors:

[cols="1,3"]
|===
a|----
A: DoA()
B: DoB()
C: DoC()
----
a|[dbdiag-spans]
----
A: DoA()
B: DoB()
C: DoC()
----
|===

Actors can have multiple concurrent operations.

[cols="1,3"]
|===
a|----
A: DoMany() M
A: One() A
A: Two() B
A: one A
A: two B
A: END M
----
.^a|[dbdiag-spans]
----
A: DoMany() M
A: One() A
A: Two() B
A: one A
A: two B
A: END M
----
|===

When multiple operations are concurrent, use markers to show how operations serialize in the given example:

[cols="1,3"]
|===
a|----
A: Push(a) A
A: END A
B: Push(b) B
A: Pop() AA
B: EVENT B
A: EVENT AA
A: b AA
B: END B
----
.^a|[dbdiag-spans]
----
A: Push(a) A
A: END A
B: Push(b) B
A: Pop() AA
B: EVENT B
A: EVENT AA
A: b AA
B: END B
----
|===

Or to put everything together:

[cols="1,3"]
|===
a|----
A: PushAll([a,b,c]) ALL
B: Push(z)
B: Pop() BZ
A: Push(a) A
A: END A
A: Push(b) B
A: EVENT B
B: EVENT BZ
A: END B
A: Push(c) C
A: END C
A: END ALL
B: Ok(b) BZ
----
.^a|[dbdiag-spans,role=fit-content]
----
A: PushAll([a,b,c]) ALL
B: Push(z)
B: Pop() BZ
A: Push(a) A
A: END A
A: Push(b) B
A: EVENT B
B: EVENT BZ
A: END B
A: Push(c) C
A: END C
A: END ALL
B: Ok(b) BZ
----
|===

== Usage

Clone github:thisismiller/dbdiag[], and it installs a script `dbdiag-spans`.  The interactive demo above is loading this script via python-in-wasm.

----
$ dbdiag-spans --help
usage: dbdiag-spans [-h] [-o OUTPUT] [--debug] [--embed] file

positional arguments:
  file                  file of operations

options:
  -h, --help            show this help message and exit
  -o OUTPUT, --output OUTPUT
                        output file path
  --debug               add extra lines to debug alignment issues
  --embed               only use 12px font and px units
----

It may be invoked as `dbdiag-spans.py [--embed] <input_file> -o <output_file.svg>`.

By default, the SVG uses the `ch` and `em` units to scale with the text size of the document.  This does not work well with any viewers or tools other than a webbrowser, so `--embed` causes only `px` to be used as units, and the font size fixed to `12px` so that lines match up with text.

The input file follows a similar syntax as the paper as well.  Each line has three parts:

`<ACTOR> [:.]? <OPERATION> [KEY]`

Where `<>` is required and `[]` is optional.

The `ACTOR` exists to group spans together.  It should either be the object being operated upon, on the entity performing the operations.  `OPERATION` is the text that will be displayed above a span.  If the text has spaces, put double quotes around it.  `KEY` can be any identifier, and the first time that a key is seen on a line, the line is interpreted as the start of the span.  The next line with the same `KEY` denotes the end of the span, and the `KEY` may then be reused.

The operation `END` is special, and not displayed.  Such spans will be shown with the starting operation text centered over the span instead.  If an operation starts and immediately finishes, you may omit the `KEY`.  This is semantically equivalent to writing an immediately following line with an `END` operation.

The operation `EVENT` is special, and will display a dot along the operation line that the given point.  This can be used to signify when the operation atomically occurred between its start and end, if needed.
