= Modern Distcc via Siso
:revdate: 2025-06-30
:draft: true
:page-category: tools
:page-hook-preamble: false

:uri-siso-psa: https://groups.google.com/a/chromium.org/g/chromium-dev/c/v-WOvWUtOpg/m/2HlNqp-6BgAJ

To lead: the title here is overly optimistic.  I do not have Siso fully working, and specifically not the remote execution part that'd make it a distcc replacement.  This is being posted so I can share work in progress notes.  It will hopefully get edited into something with a fully working setup in the future, and then fully published.

Chrome Infra team sent out a PSA that they're {uri-siso-psa}[switching from Ninja to Siso].  So what's Siso?  It bills itself as a ninja-compatible drop-in replacement which can leverage the Bazel Remote Execution and Remote Caching APIs.  All the remote compilation and caching goodness of bazel, but in the easy to use formfactor of a ninja-compatible build tool?  Sounds great!

So, let's take it for a spin.

== Building Siso

The setup that one needs to build siso is just:

----
$ git clone --depth=1 https://chromium.googlesource.com/infra/infra chrome-infra
$ cd chrome-infra/go/src/infra/build/siso
$ go build .
----

I ran into{nospace}sidenote:ref[]:
[.aside]#sidenote:def[] Filed https://issues.chromium.org/u/1/issues/428926700[bug 428926700].#

----
verifying github.com/jdxcode/netrc@v1.0.0/go.mod: checksum mismatch
	downloaded: h1:Gh9eFQJnoTNIRHXl2j5bJXA1u84hQWJWgGh569zF3v8=
	go.sum:     h1:Zi/ZFkEqFHTm7qkjyNJjaWH4LQA9LQhGJyF0lTYGpxw=
----

So I just removed the lines for `jdxcode/netrc` from `go.sum`. ¯\\_(ツ)_/¯

----
$ go build .
$ ls siso
siso
$ sudo cp $SOMEWHERE_ON_PATH
----

Success!

== Local Builds

I have a little CMake project that benchmarks a number of different cryptography libraries, and so I'm using that as my test project.  No details about what the code or CMakeLists.txt is has mattered yet, so I'm just leaving it as opaque.

Siso can be used via `siso ninja <target>`.  Our first problem is the complaint of a missing `config/siso/main.star` in the build directory:

----
$ cmake -S . -B build -G Ninja
$ cd build
$ siso ninja cryptobench
0.00s Error: can not detect exec_root: config/siso not found
$ mkdir -p config/siso
$ siso ninja cryptobench
0.01s Error: failed to load @config//main.star: open main.star: no such file or directory
----

And so we have to write a minimal `main.star`.  You can basically stub out the entire thing{nospace}sidenote:ref[] and it appears to work:
[.aside]#sidenote:def[] Filed https://issues.chromium.org/u/1/issues/428883432[bug 428883432].#

.config/siso/main.star
[source,starlark]
----
load("@builtin//struct.star", "module")

def init(ctx):
  return module(
      "config", step_config = '{"rules": []}',
      filegroups={}, handlers={})
----

And now we can successfully attempt a local build:

----
$ siso ninja cryptobench
load build.ninja... panic: runtime error: index out of range [1] with length 1

goroutine 85 [running]:
go.chromium.org/infra/build/siso/toolsupport/ninjautil.(*fileParser).setup(0xc000141808, {0x17f8858, 0xc00088c0c0})
	$HOME/ws/siso/build/siso/toolsupport/ninjautil/file_parser.go:285 +0x2b0
go.chromium.org/infra/build/siso/toolsupport/ninjautil.(*fileParser).parseContent(0xc000141808, {0x17f8858, 0xc00088c0c0})
	$HOME/ws/siso/build/siso/toolsupport/ninjautil/file_parser.go:165 +0x499
go.chromium.org/infra/build/siso/toolsupport/ninjautil.(*fileParser).parseFile(0xc000141808, {0x17f8890, 0xc0000fc410}, {0x1340e99, 0xb})
	$HOME/ws/siso/build/siso/toolsupport/ninjautil/file_parser.go:82 +0x391
go.chromium.org/infra/build/siso/toolsupport/ninjautil.(*ManifestParser).loadFile(0xc000882000, {0x17f8890, 0xc0000fc410}, {0x1340e99, 0xb})
	$HOME/ws/siso/build/siso/toolsupport/ninjautil/manifest_parser.go:88 +0x10b
go.chromium.org/infra/build/siso/toolsupport/ninjautil.(*ManifestParser).Load.func1()
	$HOME/ws/siso/build/siso/toolsupport/ninjautil/manifest_parser.go:64 +0x27
golang.org/x/sync/errgroup.(*Group).Go.func1()
	$HOME/go/pkg/mod/golang.org/x/sync@v0.13.0/errgroup/errgroup.go:79 +0x50
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1
	$HOME/go/pkg/mod/golang.org/x/sync@v0.13.0/errgroup/errgroup.go:76 +0x93
----

Err... almost.{nospace}sidenote:ref[]
[.aside]#sidenote:def[] Filed https://issues.chromium.org/u/1/issues/428883433[bug 428883433].#

Peeking at `file_parser.go:285` it's code related to `include` handling, and `build.ninja` includes `CMakeFiles/rules.ninja`.  So lets work around this by just doing the include ourself by copy-pasting the entire `rules.ninja` file where the `include` is in `build.ninja`.

----
$ siso ninja cryptobench
build finished
local:10 remote:0 cache:0 fallback:0 retry:0 skip:1
fs: ops: 1686(err:786) / r:785(err:0) 145.15MiB / w:0(err:0) 0B
E0630 14:36:12.557508 1188343 state.go:762] dir:/usr/lib64/llvm20/bin name:/usr/lib64/llvm20 entries:&directory{m:0xc00052bdc8}
E0630 14:36:12.557698 1188343 state.go:762] dir:/usr/lib/gcc/x86_64-redhat-linux/15 name:/usr/lib/gcc/x86_64-redhat-linux entries:&directory{m:0xc010fe5288}
6.28s Build Succeeded: 10 steps - 1.59/s
$ ls cryptobench
cryptobench
----

It worked!

== Remote Builds

I signed up for BuildBuddy, as they were the first hosted remote execution service I found offering a free tier.

BuildBuddy then gives you the configuration for bazel to set up remote execution:

----
build --bes_results_url=https://app.buildbuddy.io/invocation/
build --bes_backend=grpcs://remote.buildbuddy.io
build --remote_timeout=10m
build --remote_executor=grpcs://remote.buildbuddy.io
build --remote_header=x-buildbuddy-api-key=API_KEY_REDACTED
----

I think how one is supposed to hook this together is to follow the pattern from a https://github.com/bazelbuild/reclient/discussions/16#discussioncomment-12834329[bazel github issue] and a https://issues.chromium.org/issues/428661934[siso bug report] and take the API key and place it into a "credential helper" script:

.siso-credential-helper.sh 
----
#!/bin/bash

# https://www.buildbuddy.io/docs/guide-auth/
apikey="XKnFdxJHJetfq1aKExDh"
# Requires an RFC3339 date.
expires=`date --date='now +6 hours' -Iseconds`

echo "{
    \"headers\": {
        \"x-buildbuddy-api-key\": [\"${apikey}\"]
    },
    \"expires\": \"${expires}\"
}"
----

And then the invocation looks like:

.Fixed by bug 428883434
[%collapsible]
====
----
$ SISO_CREDENTIAL_HELPER=siso-credential-helper.sh siso ninja \
    -reapi_address=remote.buildbuddy.io:443 \
	-reapi_instance=default \
	-strict_remote \
reapi instance: default
0.02s Error: failed to dial remote.buildbuddy.io:443: google: could not find default credentials. See https://cloud.google.com/docs/authentication/external/set-up-adc for more information
----

So, now we get to set up gcloud credentials for some reason?

----
$ gcloud init
$ gcloud auth application-default login
----

And new we can try again:
====

----
$ SISO_CREDENTIAL_HELPER=siso-credential-helper.sh siso ninja \
    -reapi_address=remote.buildbuddy.io:443 \
	-reapi_instance=default \
	-strict_remote \
build finished
local:10 remote:0 cache:0 fallback:0 retry:0 skip:1
reapi: ops: 2(err:2) / r:0(err:0) 0B / w:0(err:0) 0B
fs: ops: 953(err:424) / r:411(err:0) 43.62MiB / w:0(err:0) 0B
E0630 18:59:09.582292 1210745 state.go:762] dir:/usr/lib64/llvm20/bin name:/usr/lib64/llvm20 entries:&directory{m:0xc011b480b8}
E0630 18:59:09.582423 1210745 state.go:762] dir:/usr/lib/gcc/x86_64-redhat-linux/15 name:/usr/lib/gcc/x86_64-redhat-linux entries:&directory{m:0xc011b0bb98}
0.91s Build Succeeded: 10 steps - 10.94/s
----

But `local:10 remote:0` makes it look like it all executed locally?{nospace}sidenote:ref[]
[.aside]#sidenote:def[] Filed https://issues.chromium.org/u/1/issues/428946258[bug 428946258].#

Poking around in `siso.INFO`, I see:

----
W0630 22:10:57.599256 1219889 retry.go:73] retry backoff:200ms: rpc error: code = Unauthenticated desc = Invalid API key "B***5"
I0630 22:10:57.903058 1219889 cas.go:335] upload 4cfbadf3f910f0a9ae5df952e47a3e23058aad61ef91427271d8e03f9f59243c/2100674 file:///home/miller/ws/duckdb/build/release/build.ninja failed: find missing: rpc error: code = Unauthenticated desc = Invalid API key "B***5"
I0630 22:10:57.903091 1219889 cas.go:335] upload d60a3ddc8f834be21cefbe22f76138124f2a03aded3eba90f8a18cdc7a5d7789/88 *remoteexecution.Directory failed: find missing: rpc error: code = Unauthenticated desc = Invalid API key "B***5"
W0630 22:10:57.903108 1219889 builder.go:850] failed to upload build files tree d60a3ddc8f834be21cefbe22f76138124f2a03aded3eba90f8a18cdc7a5d7789/88: find missing: rpc error: code = Unauthenticated desc = Invalid API key "B***5"
----

And I'm not really sure how to make progress past this...