name: middleman

on:
  workflow_call:
    inputs:
      middleman-environment:
        required: true
        type: string

jobs:
  middleman:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 17
        cache: 'npm'

    - name: Install Node Packages
      run: |
        npm install
        echo $(npm bin) >> $GITHUB_PATH

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Install Graphviz
      run: sudo apt-get install -qq graphviz
    - name: Install Pikchr
      run: |
        wget https://pikchr.org/home/tarball/trunk/pikchr.tgz
        tar -xf pikchr.tgz
        cd pikchr
        make
        echo "$(pwd)" >> $GITHUB_PATH
    - name: Install dbdiag
      run: |
        mkdir dbdiag
        cd dbdiag
        wget https://github.com/thisismiller/dbdiag/releases/download/latest/dbdiag-0.0.0-py3-none-any.whl -O dbdiag.whl
        pip install ./dbdiag.whl

    - name: Build Middleman
      run: bundle exec middleman build --verbose --environment=${{ inputs.middleman-environment }}

    - name: Sideload extra artifacts
      run: |
        mkdir build/static
        cp dbdiag/dbdiag.whl build/static

    - name: Upload Site Artifact
      uses: actions/upload-artifact@v3
      with:
        name: site
        path: ./build/
        retention-days: 1

