name: middleman

on:
  workflow_call:
    inputs:
      middleman-environment:
        required: true
        type: string

jobs:
  middleman:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v4.3.0
      with:
        node-version: 20
        cache: 'npm'

    - name: Install Node Packages
      run: |
        npm install
        echo $(npm bin) >> $GITHUB_PATH

    - name: Install Bytefield
      run: npm install --location=global bytefield-svg

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3
        bundler-cache: true

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Install Graphviz
      run: sudo apt-get install -qq graphviz
    - name: Install Pikchr
      run: |
        wget https://github.com/drhsqlite/pikchr/archive/refs/heads/master.zip
        unzip master.zip
        cd pikchr-master
        make
        echo "$(pwd)" >> $GITHUB_PATH
    - name: Install dbdiag
      run: |
        mkdir dbdiag
        cd dbdiag
        wget https://github.com/thisismiller/dbdiag/releases/latest/download/dbdiag-0.0.0-py3-none-any.whl
        pip install ./dbdiag-0.0.0-py3-none-any.whl

    # Before the build and load into source, so that asset hashing applies.
    - name: Sideload extra artifacts
      run: |
        mkdir source/static
        cp dbdiag/dbdiag-0.0.0-py3-none-any.whl source/static/dbdiag.whl

    - name: Build Middleman
      run: bundle exec middleman build --verbose --environment=${{ inputs.middleman-environment }}

    - name: Upload Site Artifact
      uses: actions/upload-artifact@v4
      with:
        name: site
        path: ./build/
        retention-days: 1

